export default    {
    products:[{
        _id:1,
        name:'The subtle art of not giving a fuck',
        genre:'Pyscology',
        image:'/images/b1.jpg',
        price:250,
        author:'Mark Manson',
        stars:4.5,
        noReviews:10,
        countInStock: 2
    },
    {    _id:2,
        name:'Harry Potter and the Prisoner of Askaban',
        genre:'Fantasy',
        image:'/images/b2.jpg',
        price:450,
        author:'J.K Rowlings',
        stars:4.5,
        noReviews:10,
        countInStock: 10
    },
    {   _id:3,
        name:'The mystery of Howgarts',
        genre:'Fantasy',
        image:'/images/b3.jpg',
        price:500,
        author:'J.K Rowlings',
        stars:4.5,
        noReviews:10,
        countInStock:8 
    },
    {
        _id:4,
        name:'The Immortals of Meluha: 1 (The Shiva Trilogy, 1)',
        genre:'Fantasy',
        image:'/images/b4.jpg',
        price:279,
        author:'Amish Tripathi',
        stars:4.5,
        noReviews:10,
        countInStock: 2
    },
    {    _id:5,
        name:'The Secret Of The Nagas',
        genre:'Fantasy',
        image:'/images/b5.jpg',
        price:450,
        author:'Amish Tripathi',
        stars:4.5,
        noReviews:10,
        countInStock: 10
    },
    {   _id:6,
        name:'The Oath of the Vayuputras (Shiva Trilogy): 3',
        genre:'Fantasy',
        image:'/images/b6.jpg',
        price:456,
        author:'Amish Tripathi',
        stars:4.5,
        noReviews:10,
        countInStock:8 
    },
    {
        _id:7,
        name:'How to Win Friends and Influence People',
        genre:'Pyscology',
        image:'/images/b7.jpg',
        price:150,
        author:'Dale Carnegie',
        stars:4.5,
        noReviews:10,
        countInStock: 2
    },
    {    _id:8,
        name:'Think Like a Monk',
        genre:'Pyscology',
        image:'/images/b8.jpg',
        price:329,
        author:'Jay Shetty',
        stars:4.5,
        noReviews:10,
        countInStock: 10
    },
    {   _id:9,
        name:'Zero to One: Notes on Start Ups, or How to Build the Future',
        genre:'Mentorship',
        image:'/images/b9.jpg',
        price:381,
        author:'Peter Thiel',
        stars:4.5,
        noReviews:10,
        countInStock:8 
    }
]
}